GET http:/localhost:3000/todo/?status=TO%20DO

###
GET http:/localhost:3000/todo/?priority=HIGH

###
GET http:/localhost:3000/todo/?priority=HIGH&status=IN%20PROGRESS

###
GET http:/localhost:3000/todo/?search_q=Play